version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: finances_dev
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - db_finances:/var/lib/postgresql/data

volumes:
  db_finances: